### PR TITLE
fix: video fixes and some appeal bugs

### LINKED ISSUE #35: Fix the issues found out in the video
- Should not display dispute if selected.
- The amount lost should be in PNK and not in 1e-18 PNK.
- Notifications should refer to the dispute ID.
- I don't understand why we just see 1 vote for partyB. We should have 3 right?
- We need to see that the party gets the ETH.
- Replace "activate" by "deposit".

### PR DESCRIPTION
**Pull request by satello**
- Rename Activate -> Deposit
- Specify Appeal Number in titles of appeal events
- Show disputeId in Notification titles
- Ruling index off by 1 for Ruling event
- Display 'No Ruling' instead of 'Party B Wins' if dispute had no ruling
- Sort events by date, with null dated events coming at the end

closes #35

### CODE REVIEW

File: src/components/notification-card/index.js [hunk 1]
```diff
@@ -4,10 +4,18 @@ import { Link } from 'react-router-dom'
...
+  message,
+  to,
+  disputeId,
+  onClick,
+  onDismissClick
+}) => {
   const content = (
     <div className="NotificationCard-message" onClick={onClick}>
-      {message}
+      <span>Dispute {disputeId}: </span>
```
Comment (epiqueras) [inline src/components/notification-card/index.js]: Unnecessary spans, they don't do anything without styling. (not block-level)

File: src/components/notification-card/index.js [hunk 2]
```diff
@@ -4,10 +4,18 @@ import { Link } from 'react-router-dom'
 
 import './notification-card.css'
 
-const NotificationCard = ({ id, message, to, onClick, onDismissClick }) => {
+const NotificationCard = ({
+  id,
+  message,
+  to,
+  disputeId,
```
Comment (epiqueras) [inline src/components/notification-card/index.js]: id,
disputeID,
message,
...

File: src/components/notification-card/index.js [hunk 3]
```diff
@@ -28,6 +36,7 @@ NotificationCard.propTypes = {
   // State
   id: PropTypes.string,
   message: PropTypes.string.isRequired,
+  disputeId: PropTypes.number,
```
Comment (epiqueras) [inline src/components/notification-card/index.js]: Should be required. Also keep the same order as in destructure.

File: src/containers/dispute/components/details/index.js [hunk 4]
```diff
@@ -82,7 +83,13 @@ Details.propTypes = {
...
   arbitrationFee: PropTypes.number.isRequired,
   arbitrableContractAddress: PropTypes.string.isRequired,
-  disputeID: PropTypes.number.isRequired
+  disputeID: PropTypes.number.isRequired,
+  appealNumber: PropTypes.number
+}
+
+Details.defaultProps = {
+  // State
+  appealNumber: null
```
Comment (epiqueras) [inline src/containers/dispute/components/details/index.js]: Should be required.

File: src/containers/dispute/components/ruling/index.js [hunk 5]
```diff
@@ -113,12 +118,14 @@ Ruling.propTypes = {
   votesForPartyB: PropTypes.number.isRequired,
   netPNK: PropTypes.number.isRequired,
   disputeID: PropTypes.number.isRequired,
-  appeals: PropTypes.number.isRequired
+  appeals: PropTypes.number.isRequired,
+  appealNumber: PropTypes.number
```
Comment (epiqueras) [inline src/containers/dispute/components/ruling/index.js]: Should be required.

File: src/sagas/dispute.js [hunk 6]
```diff
@@ -34,20 +34,29 @@ const parseDispute = d => {
...
+      appealNumber: i,
       type: disputeConstants.EVENT_TYPE_ENUM[2],
       date: a.ruledAt ? new Date(a.ruledAt) : null
     }))
   ]
-  events = events.sort((a, b) => (a.data <= b.date || a.data !== null ? -1 : 1))
+  events = events.sort(
+    (a, b) =>
+      // Put events with no date at the end. These are in progress
+      (a.date === null) - (b.date === null) ||
```
Comment (epiqueras) [inline src/sagas/dispute.js]: `(a === null || b === null ? -1 : 1) * (a - b)`
